version: "2"
services:
  # MySQL DB Container
  mysql:
    image: "mysql:latest"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    volumes:
      - ./docker-data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: local
